# include: package:pedantic/analysis_options.yaml
include: package:lints/core.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    invalid_use_of_protected_member: error
    dead_code: info
linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - constant_identifier_names
    - one_member_abstracts
    - recursive_getters
    - null_closures
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_final_fields
    - unnecessary_new
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - public_member_api_docs
